### ISSUE TITLE
Should mpicc be automatically added  

### ISSUE THREAD

**Issue by runiteking1** [Multilevel-NN/torchbraid#18]
In `setup.py`, we have 
```
if "CC" not in os.environ.keys():
  os.environ["CC"] = mpi4py.get_config()['mpicc']
```
In general, shouldn't we automatically overwrite the compiler so that `mpicc` is used every time or otherwise indicate that the correct compiler should be `mpicc`? In the case where `os.environ["CC"]` exists, it's not necessary that it's MPI aware and will cause errors in the build process for `xbraid`. We can save the preexisting environment settings and revert it once the setup is done running.

**Comment by runiteking1** [comment]
It seems that the `environ` is not [persistent](https://dagster.io/blog/python-environment-variables) and only effects any child processes (another [source](https://stackoverflow.com/questions/716011/why-cant-environmental-variables-set-in-python-persist) though I can't find any help in the official documentation). 

Confirmed via doing a dummy install and the CC compiler is restored after it installs. I'll go ahead and update the setup script then?

**Comment by eric-c-cyr** [comment]
Sure that would be great! Thanks
